name: Github CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancels previous runs of the same workflow
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        ocaml: [4.14.x, 4.13.x, 4.12.x]
        os: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🐫 Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
          dune-cache: true

      - name: 🐫🐪🐫 Get dependencies
        run: opam exec -- make opam-deps

      - name: 🧱 Build coq-lsp
        run: opam exec -- make build

  osx:
    runs-on: macOS-latest
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🐫 Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
          dune-cache: true

      - name: 🐫🐪🐫 Get dependencies
        run: opam exec -- make opam-deps

      - name: 🧱 Build coq-lsp
        run: opam exec -- make build

  client-compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./editor/code
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
      - name: 🚀 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run compile

  fmt-ocamlfmt:
    name: Format with ocamlfmt
    runs-on: ubuntu-latest
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: ❄️ Setup Nix
        uses: cachix/install-nix-action@v18
      - name: 📐 Format with ocamlfmt
        run: nix develop .#fmt -c make fmt

  fmt-prettier:
    name: Format with prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./editor/code
    steps:
      - name: 🔭 Checkout code
        uses: actions/checkout@v3
      - name: 🚀 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npx prettier -c .
